### ISSUE TITLE
Improved sslscan usage

### ISSUE THREAD

**Issue by rbsec** [1N3/MassBleed#1]
There are a number of places in the script where you're using sslscan just to check for SSLv3 ciphers, with something like this:

```
sslscan --no-failed $RANGE:$a | egrep --color=auto 'SSLv3'
```

This is making sslscan perform all of its checks, and then just discarding everything other than the SSLv3 ciphers in the output, which isn't very efficient. It should improve perfomance to specify only scanning SSLv3 (--ssl3), and disabling any other checks that some versions of sslscan perform (compression, heartbleed, renegotiation, etc). Something like this:

```
sslscan --no-heartbleed --no-compression --no-renegotiation --no-check-certificate --ssl3 --no-failed [target]
```

Some of these options don't exist in older versions, but they're just ignored by it so it doesn't break anything.

**Comment by 1N3** [comment]
hey, thanks for info! I checked in a change for this in the master project and it's definitely much faster now :+1:
